workers: 8
seed: 666
gpu: 2

encoder: 'efficientnet-b2'
decoder: 'DeepLabV3Plus'
#decoder: 'MAnet'

#data
data_path: '/storage1/nerusskikh/drivendata/stac_flood/data/train_features/'
labels_path: '/storage1/nerusskikh/drivendata/stac_flood/data/train_labels/'
supplementary_data: False
nfolds: 4

bin_borders: [0.,1.0e-3, 1.0e-2, 5.0e-2, 0.2,1.1]

#train 
epochs: 400
train_bs: 16
lr: 1.0e-4
lr_scheduler: False
loss_step: 1

smooth_label: False
labels_smooth_alpha: 0.2

tta: True
val_bs: 16
ckpt_path: '/storage1/iigor/drivendata/STAC_flood/checkpoints/'
ckpt_step: 1

train_val_step: 5

#track 
save_ckpt: True
track: True
neptune_project: 'i-igor/STAC-flood'
neptune_token: 'eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiJmNDJiZDQwYy1kNzhhLTRlYWYtYmI0Yy01ZTNhZmM0NDhlY2EifQ=='
run_tags: 
- effnetb2
#- manet
- tta
- gaussblur
- area_split
#- harder_augs
- normalization
- 3rdchannel_pp
#- tfms_then_chanproduct
#- supplementary
#- LabelSmooth
#- OneCycleScheduler